Repository lisaerikssonw/project-2-sweden, pull requests merged in 2019-06, with the labels that each got.

#52 Småändringar för att få bort varningar i console log
  public/index.html
  src/components/Footer.js
  src/components/Route.js
  src/components/RouteMap.js
  src/components/SearchForm.js
  src/components/Segment.js
  src/styles/App.css
  src/styles/search-results.css
Labels: invalid

#53 New and improved filter buttons
  src/components/SearchForm.js
  src/styles/search-form.css
Labels: enhancement

#55 Method for capitalizing first letter (segments)
  src/components/Route.js
  src/components/Segment.js
Labels: enhancement

#54 Fixed bug for Chrome not allowing uppercase for navbar
  src/components/Nav.js
  src/components/SearchForm.js
  src/styles/App.css
Labels: bug fix

#56 Added Map path and markers with animation
  public/images/icons/googlemaps.png
  src/App.js
  src/components/MainBody.js
  src/components/Route.js
  src/components/RouteMap.js
  src/components/SearchForm.js
  src/components/SearchResults.js
  src/styles/App.css
Labels: enhancement

#57 Responsive design for city articles
  package-lock.json
  public/images/aurora.jpg
  public/images/falun.jpg
  public/images/stockholm.png
  src/components/RouteMap.js
  src/styles/mainbody.css
  src/styles/mobile.css
Labels: enhancement

#59 Responsive fixes - WIP
  src/components/Route.js
  src/components/RouteMap.js
  src/components/SearchForm.js
  src/components/SearchResults.js
  src/styles/mobile.css
Labels: help wanted

#60 Made the Google map responsive in turn removing the side scrollbar
  src/components/RouteMap.js
Labels: bug fix
